name: Linux

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        swift: ['5.4']

    steps:
    - uses: actions/checkout@v2
    - uses: fwal/setup-swift@v1
      with:
        swift-version: ${{ matrix.swift }}
    - name: Install APT dependencies
      run: sudo apt-get update && sudo apt-get install -y libopus-dev libsodium-dev
    - name: Build
      run: swift build
    - name: Test
      run: swift test
